GET http://localhost:5041/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJzdWIiOiJ1c2VyIiwianRpIjoiYmQ4NDBjNCIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwNDEiLCJodHRwczovL2xvY2FsaG9zdDo3MDY2Il0sIm5iZiI6MTc2MDE5NTMxNywiZXhwIjoxNzY4MTQ0MTE3LCJpYXQiOjE3NjAxOTUzMTgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.HKloQ9LKy2Zp8WUzSQqK-ls5l3Laprdz9knyA1_JJgU

###
GET http://localhost:5041/genres/lookup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImluZyIsInN1YiI6ImluZyIsImp0aSI6ImI1NmE2YTM2Iiwicm9sZSI6InBsYXllciIsInRvcCI6IjIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MDQxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA2NiJdLCJuYmYiOjE3NjAxOTc2NDksImV4cCI6MTc2ODE0NjQ0OSwiaWF0IjoxNzYwMTk3NjUwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.HGR0xC6brzTxb5EPBYhsAYo-ZZRPP1meYv05RoKJ4gw